spring.datasource.url=jdbc:mysql://localhost:3306/back2deal?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=qwer1234!

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


jwt.secret-key=back2dealJWTSecretKeyForHS512AlgorithmVerySecureAndLongEnough1234567890
jwt.expiration=1800000
